version: '3.8'

services:
  # PostgreSQL database
  postgres:
    image: postgres:15
    environment:
      POSTGRES_DB: bankcanada_mlops
      POSTGRES_USER: admin
      POSTGRES_PASSWORD: pass
    ports:
      - "5434:5432"
    volumes:
      - postgres_data:/var/lib/postgresql/data

  # FastAPI application
  api:
    build: ./api
    ports:
      - "8002:8000"
    environment:
      - DATABASE_URL=postgresql://admin:pass@postgres:5432/bankcanada_mlops
      - REDIS_URL=redis://localhost:6379
    depends_on:
      - postgres

  # React web frontend
  web:
    build: ./web
    ports:
      - "3002:80"
    environment:
      - REACT_APP_API_URL=http://localhost:8002
    depends_on:
      - api

volumes:
  postgres_data:
