apiVersion: apps/v1
kind: Deployment
metadata:
  name: bankcanada-api
  namespace: mlops-production
  labels:
    app: bankcanada-api
    version: v1
spec:
  replicas: 1
  selector:
    matchLabels:
      app: bankcanada-api
  template:
    metadata:
      labels:
        app: bankcanada-api
        version: v1
    spec:
      containers:
      - name: api
        image: bankcanadademo.azurecr.io/bankcanada-api:latest
        ports:
        - containerPort: 8000
        env:
        - name: DATABASE_URL
          value: "postgresql://postgres:bankcanada123@postgres-service:5432/bankcanada_mlops"
        - name: REDIS_URL
          value: "redis://redis-service:6379"
        - name: MLFLOW_TRACKING_URI
          value: "http://mlflow-service:5000"
        - name: DEEPSEEK_API_KEY
          value: "placeholder-key"  # Will be configured via frontend
        - name: DATABRICKS_HOST
          value: ""  # Will be configured via frontend
        - name: DATABRICKS_TOKEN
          value: ""  # Will be configured via frontend
        resources:
          requests:
            memory: "128Mi"
            cpu: "100m"
          limits:
            memory: "256Mi"
            cpu: "200m"
        livenessProbe:
          httpGet:
            path: /health
            port: 8000
          initialDelaySeconds: 60
          periodSeconds: 30
          timeoutSeconds: 5
          failureThreshold: 5
        readinessProbe:
          httpGet:
            path: /health
            port: 8000
          initialDelaySeconds: 30
          periodSeconds: 10
          timeoutSeconds: 5
          failureThreshold: 10
      imagePullSecrets:
      - name: acr-secret
---
apiVersion: v1
kind: Secret
metadata:
  name: database-secret
  namespace: mlops-production
type: Opaque
data:
  connection-string: cG9zdGdyZXNxbDovL2FkbWluOnNlY3VyZV9wYXNzd29yZEBwb3N0Z3Jlcy1zZXJ2aWNlOjU0MzIvYmFua2NhbmFkYV9tbG9wcw==
---
apiVersion: v1
kind: Secret
metadata:
  name: api-secrets
  namespace: mlops-production
type: Opaque
data:
  deepseek-key: eW91cl9kZWVwc2Vla19hcGlfa2V5X2hlcmU=  # base64 encoded placeholder
